### ISSUE TITLE
 Excel file format cannot be determined, you must specify an engine manually

### ISSUE THREAD

**Issue by hwypengsir** [thinh-vu/vnstock#13]
Why `financial_report` can't be used in my python3?

```
from vnstock import *
df = financial_report (symbol='SSI', report_type='BalanceSheet', frequency='Quarterly')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/debian/.local/lib/python3.9/site-packages/vnstock/stock.py", line 172, in financial_report
    df = pd.read_excel(BytesIO(r.content), skiprows=7).dropna()
  File "/home/debian/.local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/debian/.local/lib/python3.9/site-packages/pandas/io/excel/_base.py", line 364, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "/home/debian/.local/lib/python3.9/site-packages/pandas/io/excel/_base.py", line 1195, in __init__
    raise ValueError(
ValueError: Excel file format cannot be determined, you must specify an engine manually.

```
Search the source code:

```
def financial_report (symbol, report_type, frequency, headers=headers): # Quarterly, Yearly
    """
    This function returns the balance sheet of a stock symbol by a Quarterly or Yearly range.
    Args:
        symbol (:obj:`str`, required): 3 digits name of the desired stock.
        report_type (:obj:`str`, required): BalanceSheet, IncomeStatement, CashFlow
        report_range (:obj:`str`, required): Yearly or Quarterly.
    """
    url = 'https://fiin-fundamental.ssi.com.vn/FinancialStatement/Download{}?language=vi&OrganCode={}&Skip=0&Frequency={}'.format(report_type, symbol, frequency)
    r = requests.get(url, headers=headers)
    df = pd.read_excel(BytesIO(r.content), skiprows=7).dropna()
    return df
```

Get the url as below:
`https://fiin-fundamental.ssi.com.vn/FinancialStatement/DownloadBalanceSheet?language=vi&OrganCode=SSI&Skip=0&Frequency=Quarterly`

Paste into browser:

```
data | null
-- | --
fileName | null
status | "Failed"
errors |  
0 | "Could not find file 'C:\\FiinTrade\\FiinTrade\\FiinTrade.Fundamental\\wwwroot\\Templates\\.xlsx'."
```

Maybe the api is broken!

**Comment by haison19952013** [comment]
I do have the same problem. Is there any workable version of vnstock?

**Comment by thinh-vu** [comment]
Hi @hwypengsir @haison19952013, this function is working properly in both the Google Colab environment and my Windows laptop. I'm not sure what the root cause of this issue is, but I will troubleshoot it as soon as possible.

**Comment by haison19952013** [comment]
I think the error can stem from the different versions of dependencies like pandas, numpy, etc.I think it's better to add the `requirement.txt` in the package so that we can work on the same version of those dependencies

**Comment by thinh-vu** [comment]
Hi @haison19952013, thank you for your suggestion!
I have just added the requirements.txt file for the Google Colab environment and the requirements-windows.txt file for Windows to the [beta branch](https://github.com/thinh-vu/vnstock/tree/beta).
Feel free to give it a try and let me know if you encounter any issues.
