### ISSUE TITLE
Unsupported format, or corrupt file: Expected BOF record; found b'{"data":'

### ISSUE THREAD

**Issue by enderphan94** [thinh-vu/vnstock#3]
Calling:
AST = financial_report (symbol= "AST", report_type='BalanceSheet', frequency='yearly')

same with "FRT" as well

Error:

```
Traceback (most recent call last):
  File "main.py", line 247, in <module>
    getRate(retail_code)
  File "main.py", line 49, in getRate
    incomeData = financial_report (symbol= bank, report_type='IncomeStatement', frequency='yearly')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/vnstock/stock.py", line 172, in financial_report
    df = pd.read_excel(BytesIO(r.content), skiprows=7).dropna()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/util/_decorators.py", line 296, in wrapper
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/io/excel/_base.py", line 304, in read_excel
    io = ExcelFile(io, engine=engine)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/io/excel/_base.py", line 867, in __init__
    self._reader = self._engines[engine](self._io)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/io/excel/_xlrd.py", line 22, in __init__
    super().__init__(filepath_or_buffer)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/io/excel/_base.py", line 351, in __init__
    self.book = self.load_workbook(filepath_or_buffer)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/io/excel/_xlrd.py", line 35, in load_workbook
    return open_workbook(file_contents=data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/xlrd/__init__.py", line 157, in open_workbook
    ragged_rows=ragged_rows,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/xlrd/book.py", line 92, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/xlrd/book.py", line 1278, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/xlrd/book.py", line 1272, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
xlrd.biffh.XLRDError: Unsupported format, or corrupt file: Expected BOF record; found b'{"data":'
```

**Comment by enderphan94** [comment]
The following codes are getting the same error ```"AST","FRT","GCB","IMH","HEX","SEC","PNG","T12","SID```

**Comment by thinh-vu** [comment]
Xin chào @enderphan94, cám ơn bạn đã gửi báo lỗi!
Sau khi kiểm tra lại hàm và nguồn cấp dữ liệu, nguyên nhân lỗi được phát hiện như sau:
1. Các mã cổ phiếu không tồn tại trong dữ liệu hệ thống của SSI bao gồm: "IMH","HEX","SEC","T12"
2. Các mã cổ phiếu cần phải thay đổi tên mã mới có thể tải được dữ liệu chính xác (Tên mã cổ phiếu > Tên mã cần sử dụng) bao gồm:
- FPT > FPTR
- AST > TASECOAIRS
- GCB > PTBD
- PNG > PNCO
- SID > SCID
Lưu ý, những thay đổi trên chỉ áp dụng với hàm tải dữ liệu từ nguồn cấp SSI.
Thân,

**Comment by enderphan94** [comment]
Not sure what's been changed but now it throws the same error for all common codes

```
financial_report (symbol='MWG', report_type='CashFlow', frequency='Quarterly')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/vnstock/stock.py", line 172, in financial_report
    df = pd.read_excel(BytesIO(r.content), skiprows=7).dropna()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/util/_decorators.py", line 296, in wrapper
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/io/excel/_base.py", line 304, in read_excel
    io = ExcelFile(io, engine=engine)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/io/excel/_base.py", line 867, in __init__
    self._reader = self._engines[engine](self._io)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/io/excel/_xlrd.py", line 22, in __init__
    super().__init__(filepath_or_buffer)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/io/excel/_base.py", line 351, in __init__
    self.book = self.load_workbook(filepath_or_buffer)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/io/excel/_xlrd.py", line 35, in load_workbook
    return open_workbook(file_contents=data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/xlrd/__init__.py", line 157, in open_workbook
    ragged_rows=ragged_rows,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/xlrd/book.py", line 92, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/xlrd/book.py", line 1278, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/xlrd/book.py", line 1272, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
xlrd.biffh.XLRDError: Unsupported format, or corrupt file: Expected BOF record; found b'<!doctyp'
```
